repositories:
 -
  path: https://github.com/ag913331/learning-devops
  branch: local1
 -
  path: https://github.com/ag913331/learning-devops
  branch: local2
build_types: ['MAYA', 'SIM', 'SIM_DEBUG', 'TEST']
base_exe_dir: /media/nas/Exe/maya
phonon_path: /data/jenkins_repos/phonon